<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domain\Export\Models\ExportTemplate;
use Illuminate\Database\Seeder;

class ExportTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $this->mpikGovernmentTemplate();
        $this->corporateEnglishTemplate();
    }

    private function mpikGovernmentTemplate(): void
    {
        ExportTemplate::withoutGlobalScopes()->updateOrCreate(
            ['is_system' => true, 'name' => 'Minit Mesyuarat Pengurusan Kerajaan (MY)'],
            [
                'description' => 'Format minit mesyuarat rasmi kerajaan Malaysia — letterhead, senarai kehadiran tiga-aras, agenda berhierarki, tag Makluman/Tindakan, pengesahan dua lajur.',
                'primary_color' => '003366',
                'font_family' => 'Arial',
                'is_default' => false,
                'organization_id' => null,
                'page_setup' => [
                    'font' => 'Arial',
                    'size' => 11,
                    'margin_top' => 1440,
                    'margin_bottom' => 1440,
                    'margin_left' => 1800,
                    'margin_right' => 1440,
                ],
                'labels' => [
                    'ms' => [
                        'present' => 'Hadir',
                        'also_present' => 'Turut Hadir',
                        'absent' => 'Tidak Hadir',
                        'action' => 'Tindakan',
                        'noted' => 'Makluman',
                        'date' => 'Tarikh',
                        'time' => 'Masa',
                        'venue' => 'Tempat',
                        'prepared_by' => 'Disediakan oleh',
                        'approved_by' => 'Disahkan/diluluskan oleh',
                        'next_meeting' => 'Mesyuarat Seterusnya',
                        'generated_by' => 'Dijana oleh antaraNote pada',
                    ],
                    'en' => [
                        'present' => 'Present',
                        'also_present' => 'Also Present',
                        'absent' => 'Absent',
                        'action' => 'Action',
                        'noted' => 'Noted',
                        'date' => 'Date',
                        'time' => 'Time',
                        'venue' => 'Venue',
                        'prepared_by' => 'Prepared by',
                        'approved_by' => 'Approved by',
                        'next_meeting' => 'Next Meeting',
                        'generated_by' => 'Generated by antaraNote on',
                    ],
                ],
                'glossary' => [],
                'blocks' => [
                    [
                        'id' => 'b-title',
                        'type' => 'title',
                        'settings' => [
                            'text' => 'MINIT MESYUARAT {{series.name}} BILANGAN {{mom_number}} TAHUN {{year}}',
                            'align' => 'center',
                        ],
                    ],
                    [
                        'id' => 'b-org',
                        'type' => 'letterhead',
                        'settings' => [
                            'logo_path' => null,
                            'align' => 'center',
                            'show_rule' => true,
                            'logo_height' => 60,
                            'lines' => ['{{organization.name}}'],
                        ],
                    ],
                    [
                        'id' => 'b-divider',
                        'type' => 'divider',
                        'settings' => ['color' => '003366', 'thickness' => 2],
                    ],
                    [
                        'id' => 'b-meta',
                        'type' => 'meta',
                        'settings' => [
                            'separator' => ':',
                            'fields' => [
                                ['label' => 'date',  'token' => '{{meeting_date|d F Y (l)}}'],
                                ['label' => 'time',  'token' => '{{start_time}} hingga {{end_time}}'],
                                ['label' => 'venue', 'token' => '{{location}}'],
                            ],
                        ],
                    ],
                    [
                        'id' => 'b-attendees',
                        'type' => 'attendees',
                        'settings' => [
                            'groups' => ['present', 'also_present', 'absent'],
                        ],
                    ],
                    [
                        'id' => 'b-agenda',
                        'type' => 'agenda',
                        'settings' => [
                            'source' => 'topics',
                            'extraction_types' => ['summary', 'topics', 'decisions', 'risks'],
                        ],
                    ],
                    [
                        'id' => 'b-action-items',
                        'type' => 'action_items',
                        'settings' => [],
                    ],
                    [
                        'id' => 'b-next-meeting',
                        'type' => 'richtext',
                        'settings' => [
                            'content' => "Mesyuarat Seterusnya\n\nTarikh & Masa : _______________________________________________\nTempat        : _______________________________________________",
                        ],
                    ],
                    [
                        'id' => 'b-signature',
                        'type' => 'signature',
                        'settings' => [
                            'columns' => [
                                ['label' => 'prepared_by', 'name' => '{{prepared_by}}', 'position' => '', 'show_date' => true],
                                ['label' => 'approved_by', 'name' => '{{chair.name}}',  'position' => '', 'show_date' => true],
                            ],
                        ],
                    ],
                    [
                        'id' => 'b-footer',
                        'type' => 'footer',
                        'settings' => ['align' => 'center'],
                    ],
                ],
            ]
        );
    }

    private function corporateEnglishTemplate(): void
    {
        ExportTemplate::withoutGlobalScopes()->updateOrCreate(
            ['is_system' => true, 'name' => 'Corporate Minutes (EN)'],
            [
                'description' => 'Clean English-language minutes template for corporate meetings.',
                'primary_color' => '4c1d95',
                'font_family' => 'Calibri',
                'is_default' => false,
                'organization_id' => null,
                'page_setup' => [
                    'font' => 'Calibri',
                    'size' => 11,
                    'margin_top' => 1440,
                    'margin_bottom' => 1440,
                    'margin_left' => 1440,
                    'margin_right' => 1440,
                ],
                'labels' => [
                    'en' => [
                        'present' => 'Present',
                        'also_present' => 'Also Present',
                        'absent' => 'Absent',
                        'prepared_by' => 'Prepared by',
                        'approved_by' => 'Approved by',
                        'generated_by' => 'Generated by antaraNote on',
                    ],
                ],
                'glossary' => [],
                'blocks' => [
                    ['id' => 'b-lh', 'type' => 'letterhead', 'settings' => ['lines' => ['{{organization.name}}'], 'align' => 'left']],
                    ['id' => 'b-t',  'type' => 'title',      'settings' => ['text' => '{{title}}', 'align' => 'left']],
                    ['id' => 'b-m',  'type' => 'meta',       'settings' => []],
                    ['id' => 'b-at', 'type' => 'attendees',  'settings' => ['groups' => ['present', 'absent']]],
                    ['id' => 'b-ag', 'type' => 'agenda',     'settings' => ['extraction_types' => ['summary', 'decisions', 'risks']]],
                    ['id' => 'b-ai', 'type' => 'action_items', 'settings' => []],
                    ['id' => 'b-sg', 'type' => 'signature',  'settings' => []],
                    ['id' => 'b-ft', 'type' => 'footer',     'settings' => []],
                ],
            ]
        );
    }
}
