<?php

declare(strict_types=1);

namespace App\Domain\Export\Blocks;

use App\Domain\Export\Models\ExportTemplate;
use App\Domain\Meeting\Models\MinutesOfMeeting;

/**
 * Carries everything a block renderer needs: the MOM data, resolved template
 * labels in the chosen output language, page setup, and the token resolver.
 */
final class ExportContext
{
    /** @var array<string, string> */
    public readonly array $labels;

    /** @var array<string, mixed> */
    public readonly array $pageSetup;

    /** @var array<int, string> */
    public readonly array $glossary;

    public readonly TokenResolver $tokens;

    public readonly Numbering $numbering;

    /** @var array<string, string> Default labels used if template has none for the chosen language. */
    private const DEFAULT_LABELS = [
        'ms' => [
            'present' => 'Hadir',
            'also_present' => 'Turut Hadir',
            'absent' => 'Tidak Hadir',
            'action' => 'Tindakan',
            'noted' => 'Makluman',
            'date' => 'Tarikh',
            'time' => 'Masa',
            'venue' => 'Tempat',
            'duration' => 'Tempoh',
            'ref' => 'Rujukan',
            'prepared_by' => 'Disediakan oleh',
            'approved_by' => 'Disahkan oleh',
            'next_meeting' => 'Mesyuarat Seterusnya',
            'generated_by' => 'Dijana oleh antaraNote pada',
        ],
        'en' => [
            'present' => 'Present',
            'also_present' => 'Also Present',
            'absent' => 'Absent',
            'action' => 'Action',
            'noted' => 'Noted',
            'date' => 'Date',
            'time' => 'Time',
            'venue' => 'Venue',
            'duration' => 'Duration',
            'ref' => 'Reference',
            'prepared_by' => 'Prepared by',
            'approved_by' => 'Approved by',
            'next_meeting' => 'Next Meeting',
            'generated_by' => 'Generated by antaraNote on',
        ],
    ];

    public function __construct(
        public readonly MinutesOfMeeting $mom,
        public readonly ExportTemplate $template,
        public readonly string $outputLanguage = 'ms',
    ) {
        $this->tokens = new TokenResolver($mom);
        $this->numbering = new Numbering;

        $templateLabels = is_array($template->labels) ? $template->labels : [];
        $langLabels = $templateLabels[$outputLanguage] ?? self::DEFAULT_LABELS[$outputLanguage] ?? self::DEFAULT_LABELS['en'];
        $this->labels = array_merge(self::DEFAULT_LABELS['en'], $langLabels);

        $this->pageSetup = is_array($template->page_setup) ? $template->page_setup : [
            'font' => $template->font_family ?: 'Arial',
            'size' => 11,
            'margin_top' => 2000,
            'margin_right' => 1440,
            'margin_bottom' => 1440,
            'margin_left' => 1440,
        ];

        $glossaryRaw = is_array($template->glossary) ? $template->glossary : [];
        $this->glossary = array_values(array_filter($glossaryRaw));
    }

    public function label(string $key): string
    {
        return $this->labels[$key] ?? $key;
    }

    public function primaryColor(): string
    {
        return ltrim($this->template->primary_color ?? '4c1d95', '#');
    }
}
