<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Action Item Status Report</title>
    <style>
        body { margin: 20px; font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; color: #1e1b4b; margin-bottom: 4px; }
        h2 { font-size: 14px; color: #4c1d95; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-top: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #f3f4f6; text-align: left; padding: 6px; font-size: 11px; border: 1px solid #e5e7eb; }
        td { padding: 6px; border: 1px solid #e5e7eb; font-size: 11px; vertical-align: top; }
        .meta { color: #6b7280; font-size: 11px; margin-bottom: 4px; }
        .stat-grid { display: table; width: 100%; margin-top: 8px; }
        .stat-cell { display: table-cell; width: 50%; text-align: center; padding: 12px; }
        .stat-value { font-size: 24px; font-weight: bold; color: #4c1d95; }
        .stat-label { font-size: 10px; color: #6b7280; margin-top: 4px; }
        .priority-low { color: #6b7280; }
        .priority-medium { color: #d97706; }
        .priority-high { color: #dc2626; }
        .priority-critical { color: #991b1b; font-weight: bold; }
        .overdue { color: #dc2626; }
        .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <h1>Action Item Status Report</h1>
    <p class="meta">{{ $template->name }}</p>
    <p class="meta">Generated: {{ now()->format('F j, Y g:i A') }}</p>

    <h2>Summary</h2>
    <div class="stat-grid">
        <div class="stat-cell">
            <div class="stat-value">{{ $totalOpen }}</div>
            <div class="stat-label">Open Items</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value overdue">{{ $totalOverdue }}</div>
            <div class="stat-label">Overdue Items</div>
        </div>
    </div>

    @if($byPriority->isNotEmpty())
        <h2>By Priority</h2>
        <table>
            <thead>
                <tr>
                    <th>Priority</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($byPriority as $priority => $items)
                    <tr>
                        <td class="priority-{{ $priority }}">{{ ucfirst($priority) }}</td>
                        <td>{{ $items->count() }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($byAssignee->isNotEmpty())
        <h2>By Assignee</h2>
        <table>
            <thead>
                <tr>
                    <th>Assignee</th>
                    <th>Open Items</th>
                </tr>
            </thead>
            <tbody>
                @foreach($byAssignee as $assignee => $items)
                    <tr>
                        <td>{{ $assignee }}</td>
                        <td>{{ $items->count() }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($openItems->isNotEmpty())
        <h2>All Open Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Assigned To</th>
                    <th>Priority</th>
                    <th>Due Date</th>
                    <th>Meeting</th>
                </tr>
            </thead>
            <tbody>
                @foreach($openItems as $item)
                    <tr>
                        <td>{{ $item->title }}</td>
                        <td>{{ $item->assignedTo?->name ?? 'Unassigned' }}</td>
                        <td class="priority-{{ $item->priority?->value ?? 'low' }}">{{ ucfirst($item->priority?->value ?? '—') }}</td>
                        <td class="{{ $item->due_date && $item->due_date->isPast() ? 'overdue' : '' }}">
                            {{ $item->due_date?->format('M j, Y') ?? '—' }}
                        </td>
                        <td>{{ $item->meeting?->title ?? '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by antaraFLOW on {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
