<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Governance Compliance Report</title>
    <style>
        body { margin: 20px; font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; color: #1e1b4b; margin-bottom: 4px; }
        h2 { font-size: 14px; color: #4c1d95; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-top: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #f3f4f6; text-align: left; padding: 6px; font-size: 11px; border: 1px solid #e5e7eb; }
        td { padding: 6px; border: 1px solid #e5e7eb; font-size: 11px; vertical-align: top; }
        .meta { color: #6b7280; font-size: 11px; margin-bottom: 4px; }
        .stat-grid { display: table; width: 100%; margin-top: 8px; }
        .stat-cell { display: table-cell; width: 25%; text-align: center; padding: 12px; }
        .stat-value { font-size: 24px; font-weight: bold; color: #4c1d95; }
        .stat-label { font-size: 10px; color: #6b7280; margin-top: 4px; }
        .good { color: #065f46; }
        .warning { color: #d97706; }
        .bad { color: #dc2626; }
        .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <h1>Governance Compliance Report</h1>
    <p class="meta">{{ $template->name }}</p>
    <p class="meta">Period: {{ $startDate->format('F j, Y') }} &mdash; {{ $endDate->format('F j, Y') }}</p>

    <h2>Compliance Overview</h2>
    <div class="stat-grid">
        <div class="stat-cell">
            <div class="stat-value">{{ $totalMeetings }}</div>
            <div class="stat-label">Total Meetings</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value {{ $quorumPercentage >= 80 ? 'good' : ($quorumPercentage >= 50 ? 'warning' : 'bad') }}">{{ $quorumPercentage }}%</div>
            <div class="stat-label">Quorum Achieved</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value">{{ $approvedCount }}</div>
            <div class="stat-label">Meetings Approved</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value">{{ $averageApprovalDays }}</div>
            <div class="stat-label">Avg. Approval Days</div>
        </div>
    </div>

    <h2>Detailed Metrics</h2>
    <table>
        <tr>
            <td><strong>Total Meetings</strong></td>
            <td>{{ $totalMeetings }}</td>
        </tr>
        <tr>
            <td><strong>Finalized / Approved</strong></td>
            <td>{{ $finalizedCount }}</td>
        </tr>
        <tr>
            <td><strong>Approved</strong></td>
            <td>{{ $approvedCount }}</td>
        </tr>
        <tr>
            <td><strong>Meetings with Quorum</strong></td>
            <td>{{ $quorumMeetings }} of {{ $totalMeetings }} ({{ $quorumPercentage }}%)</td>
        </tr>
        <tr>
            <td><strong>Approval Rate</strong></td>
            <td>{{ $approvalRate }}%</td>
        </tr>
        <tr>
            <td><strong>Average Approval Turnaround</strong></td>
            <td>{{ $averageApprovalDays }} days</td>
        </tr>
    </table>

    <div class="footer">
        Generated by antaraFLOW on {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
