<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Monthly Summary Report</title>
    <style>
        body { margin: 20px; font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 20px; color: #1e1b4b; margin-bottom: 4px; }
        h2 { font-size: 14px; color: #4c1d95; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-top: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #f3f4f6; text-align: left; padding: 6px; font-size: 11px; border: 1px solid #e5e7eb; }
        td { padding: 6px; border: 1px solid #e5e7eb; font-size: 11px; vertical-align: top; }
        .meta { color: #6b7280; font-size: 11px; margin-bottom: 4px; }
        .stat-grid { display: table; width: 100%; margin-top: 8px; }
        .stat-cell { display: table-cell; width: 25%; text-align: center; padding: 12px; }
        .stat-value { font-size: 24px; font-weight: bold; color: #4c1d95; }
        .stat-label { font-size: 10px; color: #6b7280; margin-top: 4px; }
        .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <h1>Monthly Summary Report</h1>
    <p class="meta">{{ $template->name }}</p>
    <p class="meta">Period: {{ $startDate->format('F j, Y') }} &mdash; {{ $endDate->format('F j, Y') }}</p>

    <h2>Overview</h2>
    <div class="stat-grid">
        <div class="stat-cell">
            <div class="stat-value">{{ $totalMeetings }}</div>
            <div class="stat-label">Meetings Held</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value">{{ $totalDurationMinutes ? round($totalDurationMinutes / 60, 1) : 0 }}</div>
            <div class="stat-label">Total Hours</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value">{{ $uniqueAttendees }}</div>
            <div class="stat-label">Unique Attendees</div>
        </div>
        <div class="stat-cell">
            <div class="stat-value">{{ $actionItemsCreated }}</div>
            <div class="stat-label">Action Items Created</div>
        </div>
    </div>

    <h2>Action Items</h2>
    <table>
        <tr>
            <td><strong>Created</strong></td>
            <td>{{ $actionItemsCreated }}</td>
        </tr>
        <tr>
            <td><strong>Completed</strong></td>
            <td>{{ $actionItemsCompleted }}</td>
        </tr>
        <tr>
            <td><strong>Completion Rate</strong></td>
            <td>{{ $actionItemsCreated > 0 ? round(($actionItemsCompleted / $actionItemsCreated) * 100, 1) : 0 }}%</td>
        </tr>
    </table>

    @if($meetings->isNotEmpty())
        <h2>Meetings</h2>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Date</th>
                    <th>Duration</th>
                    <th>Attendees</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($meetings as $meeting)
                    <tr>
                        <td>{{ $meeting->title }}</td>
                        <td>{{ $meeting->meeting_date?->format('M j, Y') ?? '—' }}</td>
                        <td>{{ $meeting->duration_minutes ?? '—' }} min</td>
                        <td>{{ $meeting->attendees->count() }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', $meeting->status->value)) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by antaraFLOW on {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
